### ISSUE TITLE
this.log() undefined is not a function

### ISSUE THREAD

**Issue by reggi** [yahoo/pngjs-image#3]
I'm using [blink-diff](https://github.com/yahoo/blink-diff) and i got this error. Why is it `this.log`??

```
/Users/thomas/Desktop/goldshelf/node_modules/blink-diff/node_modules/pngjs-image/index.js:24
        this.log(err.message);
             ^
TypeError: undefined is not a function
    at PNGImage.<anonymous> (/Users/thomas/Desktop/goldshelf/node_modules/blink-diff/node_modules/pngjs-image/index.js:24:14)
    at emitOne (events.js:82:20)
    at emit (events.js:166:7)
    at emitOne (events.js:82:20)
    at emit (events.js:166:7)
    at Parser._parseSignature (/Users/thomas/Desktop/goldshelf/node_modules/blink-diff/node_modules/pngjs-image/node_modules/pngjs/lib/parser.js:87:18)
    at ChunkStream._process (/Users/thomas/Desktop/goldshelf/node_modules/blink-diff/node_modules/pngjs-image/node_modules/pngjs/lib/chunkstream.js:186:23)
    at ChunkStream.write (/Users/thomas/Desktop/goldshelf/node_modules/blink-diff/node_modules/pngjs-image/node_modules/pngjs/lib/chunkstream.js:74:10)
    at PNG.write (/Users/thomas/Desktop/goldshelf/node_modules/blink-diff/node_modules/pngjs-image/node_modules/pngjs/lib/png.js:100:18)
    at ReadStream.ondata (_stream_readable.js:524:20)
thomas@workstation:goldshelf$ 
```

**Comment by marcelerz** [comment]
Fixed in #5.
