### ISSUE TITLE
v0.11.4 is not backward compatible 

### ISSUE THREAD

**Issue by nobso** [yahoo/pngjs-image#9]
<pre>
blink-diff test/screenshots/1280x800/actual/1.png test/screenshots/1280x800/expected/1.png
Blink-Diff 1.0.10
Copyright (C) 2014 Yahoo! Inc.
TypeError: Object #<Object> has no method '_readImageFromFs'
    at PNGImage.readImage (/Users/sureshkm/.nvm/v0.10.33/lib/node_modules/blink-diff/node_modules/pngjs-image/index.js:114:15)
    at /Users/sureshkm/.nvm/v0.10.33/lib/node_modules/blink-diff/node_modules/promise/lib/node-extensions.js:25:10
    at doResolve (/Users/sureshkm/.nvm/v0.10.33/lib/node_modules/blink-diff/node_modules/promise/lib/core.js:91:5)
    at new Promise (/Users/sureshkm/.nvm/v0.10.33/lib/node_modules/blink-diff/node_modules/promise/lib/core.js:71:3)
    at /Users/sureshkm/.nvm/v0.10.33/lib/node_modules/blink-diff/node_modules/promise/lib/node-extensions.js:17:12
    at Object.BlinkDiff._loadImage (/Users/sureshkm/.nvm/v0.10.33/lib/node_modules/blink-diff/index.js:704:48)
    at Object.promise.then.then._imageA (/Users/sureshkm/.nvm/v0.10.33/lib/node_modules/blink-diff/index.js:355:16)
    at /Users/sureshkm/.nvm/v0.10.33/lib/node_modules/blink-diff/node_modules/promise/lib/es6-extensions.js:18:19
    at flush (/Users/sureshkm/.nvm/v0.10.33/lib/node_modules/blink-diff/node_modules/promise/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:419:13)
</pre>

**Comment by marcelerz** [comment]
BlinkDiff was calling PNGjs-Image with an incorrect scope. Previously, ```PNGImage.readImage``` did not care what scope it was called with since it did not use ```this```, but it has changed in the most recent version. 

The bug was actually in BlinkDiff: It was calling PNGjs-Image with the global scope instead of ```PNGImage```.

```javascript
return Promise.denodeify(PNGImage.readImage)(PNGImage, path);
```
It should have been:
```javascript
return Promise.denodeify(PNGImage.readImage).call(PNGImage, path);
```

You can see above that I merged the fix in BlinkDiff and it is available in BlinkDiff 1.0.11.

Tests in PNGjs-Image could not catch this since it was doing the right thing; however, the BlinkDiff tests failed when I executed them - they just did not run since the release. I have to think about making sure that this won't happen again.

Thank you for reporting!
